from simulation.equipment.base_node import HydraulicNode
from simulation.fluid_utils import FluidProperties

class CentrifugalPump(HydraulicNode):
    """
    A Centrifugal Pump that adds pressure to the network.
    Uses the "Duty Point" methodology for engineering intuition.
    Curve: Head = A + C*Q^2 (B=0 assumed for standard pump curves)
    """
    def __init__(self, name: str, flow_rated: float, pressure_rated: float, rise_to_shutoff_pct: float = 20.0, efficiency: float = 0.75):
        super().__init__(name, node_type="centrifugal_pump")
        
        # Engineering Specs (SI Units)
        self.flow_rated = flow_rated        # m3/s
        self.pressure_rated = pressure_rated # Pa
        self.rise_pct = rise_to_shutoff_pct  # %
        self.efficiency = efficiency         # 0.0 to 1.0
        self.cavitation_warning = False

        # Internal Coefficients calculation
        self.p_shutoff = self.pressure_rated * (1.0 + self.rise_pct / 100.0)
        
        if self.flow_rated > 0:
            self.C_coeff = (self.pressure_rated - self.p_shutoff) / (self.flow_rated**2)
        else:
            self.C_coeff = 0.0

        self.add_inlet()
        self.add_outlet()

    def calculate_delta_p(self, flow_rate: float, density: float, viscosity: float = 0.001) -> float:
        """
        Calculates the pressure generated by the pump using the auto-calculated curve.
        """
        delta_p = self.p_shutoff + (self.C_coeff * (flow_rate**2))
        return max(0.0, delta_p)

    def calculate(self):
        """
        Updates the outlet port's state.
        """
        inlet = self.inlets[0]
        outlet = self.outlets[0]
        
        # Cavitation Check
        fluid_type = self.global_settings.fluid_type if self.global_settings else 'water'
        vapor_pressure = FluidProperties.get_vapor_pressure(fluid_type, inlet.temperature)
        
        # 120% margin
        npsh_safety_margin = 1.2 
        if inlet.pressure < (vapor_pressure * npsh_safety_margin):
            self.cavitation_warning = True
        else:
            self.cavitation_warning = False

        # Calculate the generated pressure
        dp = self.calculate_delta_p(inlet.flow_rate, inlet.density, inlet.viscosity)
        
        # Update outlet conditions
        outlet.pressure = inlet.pressure + dp
        outlet.flow_rate = inlet.flow_rate
        outlet.density = inlet.density
        outlet.viscosity = inlet.viscosity
        
        # Pump Waste Heat: dT = (dP / (rho * Cp)) * ((1 - eta) / eta)
        # Apply heat to the EXITING port
        cp = FluidProperties.get_specific_heat(fluid_type, inlet.temperature)
        eff_factor = (1.0 - self.efficiency) / max(0.1, self.efficiency)
        dt = (abs(dp) / (inlet.density * cp)) * eff_factor
        
        if inlet.flow_rate >= 0:
            outlet.temperature = inlet.temperature + dt
        else:
            inlet.temperature = outlet.temperature + dt

        self.calculate_temperature()
        
        return dp
