from simulation.equipment.base_node import HydraulicNode

class Pump(HydraulicNode):
    """
    A Centrifugal Pump that adds pressure to the network based on a quadratic performance curve.
    """
    def __init__(self, name: str, A: float, B: float, C: float):
        super().__init__(name, node_type="pump")
        self.A = A  # Shut-off head (meters)
        self.B = B  # Linear coefficient
        self.C = C  # Quadratic coefficient (steepness of the drop-off)
        
        self.add_inlet()
        self.add_outlet()

    def calculate_delta_p(self, flow_rate: float, density: float, viscosity: float = 0.001) -> float:
        """
        Calculates the pressure generated by the pump.
        """
        # Calculate generated head in meters using the quadratic curve
        head = self.A + (self.B * flow_rate) + (self.C * (flow_rate**2))
        
        # In a basic simulation, a pump cannot generate negative head (it doesn't act as a turbine)
        head = max(0.0, head)
        
        # Convert hydraulic head to pressure differential (Pascals)
        gravity = 9.81
        delta_p = density * gravity * head
        
        return delta_p

    def calculate(self):
        """
        Updates the outlet port's state. Note that a pump ADDS pressure.
        """
        inlet = self.inlets[0]
        outlet = self.outlets[0]
        
        # Calculate the generated pressure
        dp = self.calculate_delta_p(inlet.flow_rate, inlet.density, inlet.viscosity)
        
        # Update outlet conditions (+ dp instead of - dp)
        outlet.pressure = inlet.pressure + dp
        outlet.flow_rate = inlet.flow_rate
        outlet.density = inlet.density
        outlet.viscosity = inlet.viscosity
        
        self.calculate_temperature()
        
        return dp