from simulation.equipment.base_node import HydraulicNode
from simulation.fluid_utils import FluidProperties

class VolumetricPump(HydraulicNode):
    """
    A Volumetric (Positive Displacement) Pump.
    Maintains a nearly constant flow rate, limited by motor power and efficiency.
    """
    def __init__(self, name: str, flow_rated: float, motor_power: float, efficiency: float):
        super().__init__(name, node_type="volumetric_pump")
        self.flow_rated = flow_rated    # Rated flow (m³/s)
        self.motor_power = motor_power  # Rated power (W)
        self.efficiency = efficiency    # Decimal efficiency (0.0 to 1.0)
        self.cavitation_warning = False
        
        # Internal slip parameter to allow solver convergence.
        # This makes the dP curve very steep but not vertical.
        if flow_rated > 0:
            self.slip_factor = (0.01 * flow_rated) / 10_000_000.0 
        else:
            self.slip_factor = 1e-12

        self.add_inlet()
        self.add_outlet()

    def calculate_delta_p(self, flow_rate: float, density: float, viscosity: float = 0.001) -> float:
        """
        Calculates the pressure generated by the volumetric pump.
        Includes a smooth penalty for reverse flow to assist solver convergence.
        """
        # Hard Safety Cap (200 bar)
        hard_cap = 20_000_000.0 

        # 1. Handle Reverse Flow (Check Valve behavior)
        # Instead of a hard step, we use a very high resistance (R = hard_cap / Q_rated)
        # This ensures the solver has a continuous gradient to follow.
        if flow_rate < 0:
            reverse_resistance = hard_cap / (self.flow_rated if self.flow_rated > 0 else 1e-3)
            # Pressure boost becomes very high to resist backflow
            return hard_cap - (reverse_resistance * flow_rate)

        # 2. Theoretical dP from slip curve (Q = Q_rated - slip * dP)
        # dP = (Q_rated - Q) / slip
        if flow_rate < self.flow_rated:
            dp_curve = (self.flow_rated - flow_rate) / self.slip_factor
        else:
            dp_curve = 0.0

        # 3. Limit by Motor Power
        # Avoid division by zero
        safe_q = max(flow_rate, 1e-9)
        dp_power_limit = (self.motor_power * self.efficiency) / safe_q
        
        # The actual dP is the minimum of these limits
        delta_p = min(dp_curve, dp_power_limit, hard_cap)
        
        return max(0.0, delta_p)

    def calculate(self):
        """
        Updates the outlet port's state.
        """
        inlet = self.inlets[0]
        outlet = self.outlets[0]
        
        # Cavitation Check
        fluid_type = self.global_settings.fluid_type if self.global_settings else 'water'
        vapor_pressure = FluidProperties.get_vapor_pressure(fluid_type, inlet.temperature)
        
        npsh_safety_margin = 1.2
        if inlet.pressure < (vapor_pressure * npsh_safety_margin):
            self.cavitation_warning = True
        else:
            self.cavitation_warning = False

        # Calculate the generated pressure
        dp = self.calculate_delta_p(inlet.flow_rate, inlet.density, inlet.viscosity)
        
        # Update outlet conditions
        outlet.pressure = inlet.pressure + dp
        outlet.flow_rate = inlet.flow_rate
        outlet.density = inlet.density
        outlet.viscosity = inlet.viscosity
        
        self.calculate_temperature()
        
        return dp
