from simulation.equipment.base_node import HydraulicNode
from simulation.fluid_utils import FluidProperties
import math

class VolumetricPump(HydraulicNode):
    """
    A Volumetric (Positive Displacement) Pump.
    Maintains flow near its target, limited by power and mechanical strength.
    Designed to be mathematically 'smooth' for solver convergence.
    """
    def __init__(self, name: str, flow_rated: float, motor_power: float, efficiency: float):
        super().__init__(name, node_type="volumetric_pump")
        self.flow_rated = flow_rated    # Target Flow (m³/s)
        self.motor_power = motor_power  # Rated power (W)
        self.efficiency = efficiency    # Decimal efficiency
        self.cavitation_warning = False
        
        self.add_inlet()
        self.add_outlet()

    def calculate_delta_p(self, flow_rate: float, density: float, viscosity: float = 0.001) -> float:
        """
        Calculates pressure generated by the pump.
        Uses a steep but continuous sigmoid-like curve.
        """
        # 1. Constants for smoothness
        hard_cap = 20_000_000.0  # 200 bar
        
        # 'Stiffness' of the pump curve. A very high value makes it act like 
        # a true PD pump. We pick a value that gives 100 bar per 1% flow error.
        # stiffness = 1e7 Pa / (0.01 * flow_rated)
        if self.flow_rated > 0:
            stiffness = 10_000_000.0 / (0.01 * self.flow_rated)
        else:
            stiffness = 1e12

        # 2. Base Displacement Pressure (The "Spring" that pushes fluid)
        # dP = stiffness * (Target_Flow - Actual_Flow)
        dp_displacement = max(0.0, stiffness * (self.flow_rated - flow_rate))

        # 3. Motor Power Limit (Smooth Hyperbola)
        # P = dP * Q => dP_max = P_avail / Q
        available_power = self.motor_power * self.efficiency
        # Use a safe denominator to avoid division by zero
        safe_q = math.sqrt(flow_rate**2 + 1e-10)
        dp_power_limit = available_power / safe_q

        # 4. Handle Reverse Flow (Extreme Resistance)
        if flow_rate < 0:
            # Act like a stiff check-valve
            return hard_cap - (stiffness * flow_rate)

        # 5. Combined Model using 'Soft Min' to keep derivatives continuous
        # We want dP = min(dp_displacement, dp_power_limit, hard_cap)
        # But min() has a corner. We'll use a simpler approach:
        
        # If displacement pressure is higher than power limit, it's capped.
        delta_p = dp_displacement
        if delta_p > dp_power_limit:
            delta_p = dp_power_limit
        
        # Apply the physical hard cap
        if delta_p > hard_cap:
            delta_p = hard_cap
            
        # If flow is HIGHER than rated, displacement pressure becomes negative.
        # This is correct: the pump resists being 'pushed' faster than its speed.
        
        return delta_p

    def calculate(self):
        inlet = self.inlets[0]
        outlet = self.outlets[0]
        
        # Cavitation Check
        fluid_type = self.global_settings.fluid_type if self.global_settings else 'water'
        vapor_pressure = FluidProperties.get_vapor_pressure(fluid_type, inlet.temperature)
        
        npsh_safety_margin = 1.2
        if inlet.pressure < (vapor_pressure * npsh_safety_margin):
            self.cavitation_warning = True
        else:
            self.cavitation_warning = False

        dp = self.calculate_delta_p(inlet.flow_rate, inlet.density, inlet.viscosity)
        
        outlet.pressure = inlet.pressure + dp
        outlet.flow_rate = inlet.flow_rate
        outlet.density = inlet.density
        outlet.viscosity = inlet.viscosity
        
        # Pump Waste Heat: dT = (dP / (rho * Cp)) * ((1 - eta) / eta)
        # Apply heat to the EXITING port
        cp = FluidProperties.get_specific_heat(fluid_type, inlet.temperature)
        eff_factor = (1.0 - self.efficiency) / max(0.1, self.efficiency)
        dt = (abs(dp) / (inlet.density * cp)) * eff_factor
        
        if inlet.flow_rate >= 0:
            outlet.temperature = inlet.temperature + dt
        else:
            inlet.temperature = outlet.temperature + dt

        self.calculate_temperature()
        return dp
